/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dominio.Pokemon;
import java.awt.Color;
import javax.swing.JPanel;
import views.PanelImage;

/**
 *
 * @author Joe
 */
public class CardPokemon extends javax.swing.JPanel {

    private Pokemon miPokemon; // delcaración de mi clase con variabla a tipo objeto

    /**
     * Creates new form CardPokemon
     */
    public CardPokemon(Pokemon pk) {
        initComponents();
        this.miPokemon = pk;
        llenarTarjeta();
    }

    private void llenarTarjeta() {
        this.pkName.setText(this.miPokemon.getName());
        this.pkSpecies.setText(this.miPokemon.getSpecies());
        this.pkColor.setText(this.miPokemon.getColor());
        this.pkHabitat.setText(this.miPokemon.getHabitat());
        //this.contenedorImagen.setBackground(Color.getColor(this.miPokemon.getColor()));
        PanelImage pImage = new PanelImage(
                Integer.parseInt(this.miPokemon.getId()),
                this.miPokemon.getColor()
        );
        this.pkImagen.setViewportView(pImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pkSpecies = new javax.swing.JLabel();
        pkName = new javax.swing.JLabel();
        pkColor = new javax.swing.JLabel();
        pkHabitat = new javax.swing.JLabel();
        pkName1 = new javax.swing.JLabel();
        pkSpecies1 = new javax.swing.JLabel();
        pkColor1 = new javax.swing.JLabel();
        pkHabitat1 = new javax.swing.JLabel();
        pkImagen = new javax.swing.JScrollPane();
        btnFavorito = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(250, 450));
        setMinimumSize(new java.awt.Dimension(250, 450));
        setPreferredSize(new java.awt.Dimension(250, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pkSpecies.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pkSpecies.setForeground(new java.awt.Color(102, 102, 102));
        pkSpecies.setText("Species:");
        add(pkSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 110, -1));

        pkName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pkName.setForeground(new java.awt.Color(102, 102, 102));
        pkName.setText("Name:");
        add(pkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 96, -1));

        pkColor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pkColor.setForeground(new java.awt.Color(102, 102, 102));
        pkColor.setText("Color:");
        add(pkColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 114, -1));

        pkHabitat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pkHabitat.setForeground(new java.awt.Color(102, 102, 102));
        pkHabitat.setText("Habitat:");
        add(pkHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 114, -1));

        pkName1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pkName1.setForeground(new java.awt.Color(102, 102, 102));
        pkName1.setText("Name:");
        add(pkName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 64, -1));

        pkSpecies1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pkSpecies1.setForeground(new java.awt.Color(102, 102, 102));
        pkSpecies1.setText("Species:");
        add(pkSpecies1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 64, -1));

        pkColor1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pkColor1.setForeground(new java.awt.Color(102, 102, 102));
        pkColor1.setText("Color:");
        add(pkColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 64, -1));

        pkHabitat1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pkHabitat1.setForeground(new java.awt.Color(102, 102, 102));
        pkHabitat1.setText("Habitat:");
        add(pkHabitat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 64, -1));

        pkImagen.setBackground(new java.awt.Color(0, 0, 0));
        pkImagen.setForeground(new java.awt.Color(0, 0, 0));
        pkImagen.setMaximumSize(new java.awt.Dimension(250, 220));
        pkImagen.setMinimumSize(new java.awt.Dimension(250, 220));
        pkImagen.setPreferredSize(new java.awt.Dimension(250, 220));
        add(pkImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 220));

        btnFavorito.setBackground(new java.awt.Color(255, 255, 204));
        btnFavorito.setForeground(new java.awt.Color(153, 153, 0));
        btnFavorito.setText("Favorito");
        btnFavorito.setBorderPainted(false);
        btnFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritoActionPerformed(evt);
            }
        });
        add(btnFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritoActionPerformed
        System.out.println("Registrar pokemon como favorito: " + this.miPokemon.toString());
    }//GEN-LAST:event_btnFavoritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFavorito;
    private javax.swing.JLabel pkColor;
    private javax.swing.JLabel pkColor1;
    private javax.swing.JLabel pkHabitat;
    private javax.swing.JLabel pkHabitat1;
    private javax.swing.JScrollPane pkImagen;
    private javax.swing.JLabel pkName;
    private javax.swing.JLabel pkName1;
    private javax.swing.JLabel pkSpecies;
    private javax.swing.JLabel pkSpecies1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the miPokemon
     */
    public Pokemon getMiPokemon() {
        return miPokemon;
    }

    /**
     * @param miPokemon the miPokemon to set
     */
    public void setMiPokemon(Pokemon miPokemon) {
        this.miPokemon = miPokemon;
    }
}
