/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Joe
 */
public class PanelImage extends javax.swing.JPanel {
    private int indx;
    private String color;
    /**
     * Creates new form PanelImage
     */
    public PanelImage(int indx, String color) {
        initComponents();
        this.indx = indx;
        this.color = color;
        ventanaPokedex();
    }
//Manejo de la imagen
    
    private BufferedImage bufferI;
    private Image imagenI;
    
    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) this.getGraphics();
        g2.drawImage(
            this.bufferI, 
            2, 
            2, 
            206,
            206, 
            null
        );
    }
    
    private void ventanaPokedex() {
        try {
            //this.imagenI = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
            this.imagenI = ImageIO.read(new File("C:\\libs\\MySQL folder\\datos\\imagenes\\black-white.png"));
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        this.bufferI = new BufferedImage(206, 206,BufferedImage.TYPE_INT_ARGB);
        dibujaElPokemonQueEstaEnLaPosicion();
    }
    
     private void dibujaElPokemonQueEstaEnLaPosicion() {
        int fila = this.indx / 31;
        int columna = this.indx % 31;
        Graphics2D g2 = (Graphics2D) this.bufferI.getGraphics();
        g2.setColor(Color.WHITE);
        g2.fillRect( 1, 1, 206, 206 );
        g2.drawImage(
            this.imagenI,
            1, //posicion X inicial dentro del jpanel 
            1, // posicion Y inicial dentro del jpanel
            206, //ancho del jpanel
            206, //alto del jpanel
            columna * 96, //posicion inicial X dentro de la imagen de todos los pokemon
            fila * 96, //posicion inicial Y dentro de la imagen de todos los pokemon
            columna * 96 + 96, //posicion final X
            fila * 96 + 96, //posicion final Y
            null //si no lo pones no va
        );
        repaint();
    }
    //Fin manejo de imagen
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(206, 206));
        setMinimumSize(new java.awt.Dimension(206, 206));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
