/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.*;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import views.CardPokemon;
import datos.PokemonDB;
import dominio.Pokemon;
import java.util.ArrayList;

/**
 *
 * @author Joe
 */
public class Principal extends javax.swing.JFrame {

    private ArrayList<Pokemon> listaPokemon;
    private ArrayList<Pokemon> listaPokemonAx;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        PokemonDB pkbd = new PokemonDB();
        this.listaPokemon = (ArrayList<Pokemon>) pkbd.select();
        this.listaPokemonAx = this.listaPokemon;
        llenadoPanel();
    }

    int page = 1;
    int max = 9;
    int base = 9;
    boolean flag = false;

    private void llenadoPanel() {
        try {
            JPanel pContenedor = new JPanel();
            pContenedor.setLayout(new GridLayout(3, 3, 10, 10));
            System.out.println("LlenandoPanel de pokemon>> pagina: " + page + ", base: " + base + " maximo: " + max);
            for (int i = (max - base); i < max; i++) {
                CardPokemon cardPoke = new CardPokemon(listaPokemon.get(i));
                pContenedor.add(cardPoke);
            }
            this.Contenedor.setViewportView(pContenedor);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void buscarPokemon() {
        try {
            JPanel pContenedor = new JPanel();
            int filas = base < 3 ? 1 : 3;
            System.out.println("Buscando pokemon>> pagina: " + page + ", base: " + base + " maximo: " + max);
            pContenedor.setLayout(new GridLayout(filas, 3, 10, 10));
            for (int i = (max - base); i < max; i++) {
                CardPokemon cardPoke = new CardPokemon(listaPokemonAx.get(i));
                pContenedor.add(cardPoke);
            }
            this.Contenedor.setViewportView(pContenedor);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jFiltro = new javax.swing.JComboBox<>();
        btnSearch1 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JScrollPane();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lbPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setForeground(new java.awt.Color(0, 0, 153));
        txtSearch.setCaretColor(new java.awt.Color(0, 0, 153));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(0, 0, 153));
        btnSearch.setText("Buscar");

        jFiltro.setBackground(new java.awt.Color(204, 204, 204));
        jFiltro.setForeground(new java.awt.Color(0, 0, 102));
        jFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Color", "Habitat", "Rate de Captura", "Experiencia", "Especie" }));
        jFiltro.setAutoscrolls(true);
        jFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFiltroActionPerformed(evt);
            }
        });

        btnSearch1.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch1.setForeground(new java.awt.Color(0, 0, 153));
        btnSearch1.setText("Filtro");

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setForeground(new java.awt.Color(255, 255, 255));
        Contenedor.setMaximumSize(new java.awt.Dimension(800, 750));
        Contenedor.setMinimumSize(new java.awt.Dimension(800, 750));
        Contenedor.setOpaque(false);

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbPage.setText("Page.  1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente))
                    .addComponent(Contenedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar))
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch1)
                            .addComponent(jFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnSearch1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(lbPage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        page++;
        max = page * 9;

        if (max > listaPokemon.size() && !flag) {
            max = listaPokemon.size();
            page--;
        }

        if (max > listaPokemonAx.size() && flag) {
            max = listaPokemonAx.size();
            page--;
        }

        if (flag) {
            buscarPokemon();
        } else {
            llenadoPanel();
        }
        this.lbPage.setText("Page. " + page);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        page--;
        max = page * 9;
        if (max < 1) {
            max = 9;
            page++;
        }
        if (listaPokemon.size() < 9 && !flag) {
            max = listaPokemon.size();
            page = 1;
        }

        if (listaPokemonAx.size() < 9 && flag) {
            max = listaPokemonAx.size();
            page = 1;
        }

        if (flag) {
            buscarPokemon();
        } else {
            llenadoPanel();
        }
        this.lbPage.setText("Page. " + page);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        page = 1;
        max = 9;
        base = 9;
        String txt = this.txtSearch.getText();
        if (txt.length() < 1) {
            flag = false;
            llenadoPanel();
        } else if (txt.length() >= 1) {
            flag = true;
            this.listaPokemonAx = new ArrayList<Pokemon>();
            for (Pokemon pk : this.listaPokemon) {
                if (this.jFiltro.getSelectedItem().toString().equals("Nombre") && pk.getName().toUpperCase().contains(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }
                if (this.jFiltro.getSelectedItem().toString().equals("Color") && pk.getColor().toUpperCase().equals(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }
                if (this.jFiltro.getSelectedItem().toString().equals("Habitat") && pk.getHabitat().toUpperCase().equals(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }
                if (this.jFiltro.getSelectedItem().toString().equals("Rate de Captura") && pk.getCapture_rate().toUpperCase().equals(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }
                if (this.jFiltro.getSelectedItem().toString().equals("Experiencia") && pk.getBase_experience().toUpperCase().equals(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }
                if (this.jFiltro.getSelectedItem().toString().equals("Especie") && pk.getSpecies().toUpperCase().equals(txt.toUpperCase())) {
                    this.listaPokemonAx.add(pk);
                }

            }
            if (listaPokemonAx.size() < 9) {
                base = listaPokemonAx.size();
                max = listaPokemonAx.size();
            }
            buscarPokemon();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Contenedor;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSearch1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> jFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPage;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
